const GET_CART_CONTENTS = 'GET_CART_CONTENTS';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const REPLACE_CART = 'REPLACE_CART';

export {
    GET_CART_CONTENTS,
    ADD_TO_CART,
    REPLACE_CART,
    REMOVE_FROM_CART
}